# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nivaldoandrade
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serveless-aws-cognito

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  architecture: arm64
  environment:
    COGNITO_CLIENT_ID: !Ref UserPoolClient
    COGNITO_CLIENT_SECRET: !GetAtt UserPoolClient.ClientSecret

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${sls:stage}-UserPool
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${sls:stage}-UserPoolClient
        UserPoolId: !Ref UserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
        GenerateSecret: true
        AccessTokenValidity: 1
        RefreshTokenValidity: 7
        TokenValidityUnits:
          AccessToken: days
          RefreshToken: days
        RefreshTokenRotation:
          Feature: ENABLED
          RetryGracePeriodSeconds: 0

functions:
  signUp:
    handler: src/functions/signUp.handler
    events:
      - httpApi:
          method: post
          path: /auth/sign-up
  confirmSignUp:
    handler: src/functions/confirmSignUp.handler
    events:
      - httpApi:
          method: post
          path: /auth/confirm-signup
  signIn:
    handler: src/functions/signIn.handler
    events:
      - httpApi:
          method: post
          path: /auth/sign-in
  refreshToken:
    handler: src/functions/refreshToken.handler
    events:
      - httpApi:
          method: post
          path: /auth/refresh-token
