# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nivaldoandrade
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serveless-aws-cognito

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  architecture: arm64

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - httpApi:
          path: /
          method: get
